name: "Main"

on:
  workflow_dispatch

jobs:
  source-code-analysis:
    name: "Analysis"
    uses: Drastyn/actions/.github/workflows/source-code-analysis.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
